# Generated by Django 4.0.4 on 2022-05-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='product',
        ),
        migrations.AddField(
            model_name='wantbuyproduct',
            name='product_in_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.cart'),
        ),
    ]
