# Generated by Django 4.0.4 on 2022-05-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.TextField(choices=[('InCart', 'In Cart'), ('Accepting', 'Accepting'), ('Taking', 'Taking'), ('Deliverying', 'Deliverying'), ('Receiving', 'Receiving'), ('Done', 'Done')], default='Accepting'),
        ),
        migrations.DeleteModel(
            name='WantBuyProduct',
        ),
    ]
