# Generated by Django 4.0.4 on 2022-05-12 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cart_status_delete_wantbuyproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='WantBuyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('InCart', 'In Cart'), ('Accepting', 'Accepting'), ('Taking', 'Taking'), ('Deliverying', 'Deliverying'), ('Receiving', 'Receiving'), ('Done', 'Done')], default='Accepting')),
                ('product_in_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.cart')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
