# Generated by Django 4.0.4 on 2022-05-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_cart_status_cart_quantity_wantbuyproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantbuyproduct',
            name='status',
            field=models.TextField(choices=[('Accepting', 'Accepting'), ('Taking', 'Taking'), ('Deliverying', 'Deliverying'), ('Receiving', 'Receiving'), ('Done', 'Done')], default='Accepting'),
        ),
    ]
