# Generated by Django 4.0.4 on 2022-05-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalproducts',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
