# Generated by Django 4.0.4 on 2022-05-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalproducts',
            name='count_sold',
            field=models.IntegerField(default=1),
        ),
    ]
